---
- name: Listar actualizaciones disponibles en RHEL
  hosts: linux
  become: true
  gather_facts: false

  tasks:

    - name: Obtener lista de paquetes actualizables
      ansible.builtin.command:
        cmd: dnf list updates
      register: updates
      changed_when: false
      failed_when: updates.rc != 0

    - name: Mostrar actualizaciones
      ansible.builtin.debug:
        var: updates.stdout_lines
