---
- name: Aplicar parches de seguridad detectados previamente
  hosts: linux
  become: true
  gather_facts: false

  tasks:

    - name: Validar artifact del Workflow
      ansible.builtin.assert:
        that:
          - security_patch_plan is defined
        fail_msg: >
          No se recibió security_patch_plan desde el paso anterior.

    - name: Obtener plan correspondiente al host
      ansible.builtin.set_fact:
        host_patch_plan: "{{ security_patch_plan[inventory_hostname] }}"

    - name: Mostrar parches que serán aplicados
      ansible.builtin.debug:
        msg:
          - "Host: {{ inventory_hostname }}"
          - "CVE: {{ host_patch_plan.cves }}"
          - "RHSA: {{ host_patch_plan.rhsas }}"
          - "Paquetes: {{ host_patch_plan.packages }}"

    - name: Aplicar únicamente los paquetes detectados
      ansible.builtin.dnf:
        name: "{{ host_patch_plan.packages }}"
        state: present
        update_only: true
      when:
        - host_patch_plan.patches_required | bool
        - host_patch_plan.packages | length > 0

    - name: Informar que no existen actualizaciones de seguridad
      ansible.builtin.debug:
        msg: >
          El servidor {{ inventory_hostname }}
          no tiene actualizaciones de seguridad pendientes.
      when:
        - not host_patch_plan.patches_required | bool
