---
- name: Habilitar puerto 22 SSH en Windows Server 2025
  hosts: windows
  gather_facts: false

  tasks:
    - name: Comprobar si existe regla SSH
      ansible.windows.win_shell: |
        $rule = Get-NetFirewallRule -DisplayName "Allow SSH TCP 22" -ErrorAction SilentlyContinue

        if (-not $rule) {
            New-NetFirewallRule `
              -DisplayName "Allow SSH TCP 22" `
              -Description "Permitir conexiones SSH entrantes por TCP 22" `
              -Direction Inbound `
              -Protocol TCP `
              -LocalPort 22 `
              -Action Allow `
              -Profile Any

            Write-Output "CREATED"
        }
        else {
            Enable-NetFirewallRule -DisplayName "Allow SSH TCP 22"
            Write-Output "EXISTS"
        }
      register: firewall_result
      changed_when: "'CREATED' in firewall_result.stdout"

    - name: Mostrar resultado
      ansible.builtin.debug:
        var: firewall_result.stdout_lines
