---
- name: Habilitar puerto 22 SSH en Windows Server 2025
  hosts: windows
  gather_facts: false

  tasks:
    - name: Crear regla para permitir SSH TCP 22
      community.windows.win_firewall_rule:
        name: "Allow SSH TCP 22"
        description: "Permitir conexiones SSH entrantes por TCP 22"
        localport: "22"
        protocol: tcp
        direction: in
        action: allow
        profiles:
          - domain
          - private
          - public
        state: present
        enabled: true
