---
- name: Configurar PowerShell como DefaultShell de OpenSSH
  hosts: windows
  gather_facts: false

  tasks:
    - name: Configurar PowerShell como shell por defecto de OpenSSH
      ansible.windows.win_regedit:
        path: HKLM:\SOFTWARE\OpenSSH
        name: DefaultShell
        data: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
        type: string
        state: present

    - name: Reiniciar servicio OpenSSH
      ansible.windows.win_service:
        name: sshd
        state: restarted
